//Tested
@baseUrl = https://localhost:7162/api/
@userId = ba678a48-cb52-40ba-bb18-ac7a1de4f80f
@jwtToken = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiUGF1bFIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDbGllbnQiLCJzdWIiOiJiYTY3OGE0OC1jYjUyLTQwYmEtYmIxOC1hYzdhMWRlNGY4MGYiLCJleHAiOjE3MDA1NjA5ODd9.Vp0LzVf-ZGZVqkzEasv3hJKS0raySdq7rdQkyPH1w4v7pFyKklhK01IabU3873fKhIu0n1HOdzF9lXGEwccBVQ
@carid = 7906d674-b4f6-4679-ab60-f22e42fd1f10

###
GET {{baseUrl}}car/getall
###
GET {{baseUrl}}car/getbyid?id={{carid}}

###
GET {{baseUrl}}car/getowned?id={{userId}}
Authorization: Bearer {{jwtToken}}

###
POST {{baseUrl}}car/store
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "userid": "{{userId}}",
  "type": 0,
  "make": "Toyota",
  "model": "Corolla",
  "year": "2008",
  "vin": null,
  "color": "Prussian Blue",
  "bodytype": "4 door sedan",
  "fueltype": "Petrol",
  "transmissiontype": null,
  "enginetype": null,
  "horsepower": null,
  "torque": null,
  "fuelefficiency": null,
  "acceleration": null,
  "topspeed": null,
  "imageurls": null
}

###
PUT {{baseUrl}}car/update
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "carid": "c22b7b4b-df98-4d65-b7eb-0e88f7c57d03",
  "userid": "{{userId}}",
  "make": "Toyota",
  "model": "Corolla",
  "year": null,
  "vin": null,
  "color": null,
  "bodytype": null,
  "fueltype": null,
  "transmissiontype": null,
  "enginetype": null,
  "horsepower": null,
  "torque": null,
  "fuelefficiency": null,
  "acceleration": null,
  "topspeed": 117,
  "imageurls": null
}
###
DELETE {{baseUrl}}car/delete
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "userId": "{{userId}}",
  "carId": "{{carid}}"
}