//Tested
@baseUrl = https://localhost:7162/api/
@jwtToken = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiUGF1bFIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDbGllbnQiLCJzdWIiOiJiYTY3OGE0OC1jYjUyLTQwYmEtYmIxOC1hYzdhMWRlNGY4MGYiLCJleHAiOjE3MDA1NjA5ODd9.Vp0LzVf-ZGZVqkzEasv3hJKS0raySdq7rdQkyPH1w4v7pFyKklhK01IabU3873fKhIu0n1HOdzF9lXGEwccBVQ
@userId = 9033739a-9ebe-4624-87eb-1269a21f02bb

#Tested except delete
###
GET {{baseUrl}}user/details?id=9033739a-9ebe-4624-87eb-1269a21f02bb
Authorization: Bearer {{jwtToken}}
###
//Register User
POST {{baseUrl}}user/register
Content-Type: application/json

{
  "userName": "PaulR",
  "email": "paulr756756@gmail.com",
  "password": "HUGHjackman756",
  "confirmPassword": "HUGHjackman756",
  "address": null,
  "firstName": "Rahul",
  "lastName": "Paul",
  "phone": "9319445315",
  "dateOfBirth": null
}
###

POST {{baseUrl}}user/verify
Content-Type: application/json

{
  "email": "paulr756756@gmail.com",
  "token": "C883C0F6B7B3131B18A721D459187897559503952DA200ED68BCE255EE2E9709BC91CFAF6BB5C67EDC86A4E787D55B57D536E99C8BE4B50A5E4E3D975F93D260"
}

###
//Login user

POST {{baseUrl}}user/login
Content-Type: application/json

{
  "email": "paulr756756@gmail.com",
  "password": "string"
}
###
//Update user
PUT {{baseUrl}}user/update
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "userId": "9033739a-9ebe-4624-87eb-1269a21f02bb",
  "userName": "PaulR",
  "email": "paulr756756@gmail.com",
  "address": "B-1407, Amrapali Green, Vaibhav Khand @; Indirapuram, Ghaziabad, Uttar Pradesh-201014",
  "firstName": null,
  "lastName": null,
  "phone": null,
  "dateOfBirth": null
}
###
//Forgot Password
POST {{baseUrl}}user/forgot-password
Content-Type: application/json


"paulr756756@gmail.com"

###
POST {{baseUrl}}user/reset-password
Content-Type: application/json

{
  "token": "8C43D84FF419DBDD72B3414C4ADBB50BF3120D57F56D2CEBC943B9B4DD763BC5B7FB3FAE48D9411EC638E6A89353E422CD86D1B7E94807D0004186EF4A27DB05",
  "password": "string",
  "confirmPassword": "string"
}

###
DELETE {{baseUrl}}user/delete
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "email": "paulr756756@gmail.com",
  "password": "string",
  "confirmPassword": "string"
}